### ISSUE TITLE
[www] Hydration errors when applying default filter in `/garden`

### ISSUE THREAD

**Issue by mwskwong** [LekoArts/portfolio-v2#50]
Just to let you know. Since my site also has a similar feature so figuring out a solution/workaround will benefit both of us.

For example, in https://www.lekoarts.de/garden?tags=elitepvpers, if you navigate to this page directly with the search params, there will be a few hydrations errors due to the SSRed HTML doesn't match the displayed content after filters are applied.

This should be mostly related to
https://github.com/LekoArts/portfolio-v2/blob/main/www/src/hooks/use-query-string.tsx

My guess is that `setTimeout` is intended to workaround the hydration issue and implement low priority change. Yet, I guess the timeout is not enough to wait until hydration is complete.

I've also made use of `startTransition`, and unfortunately doesn't work around the issue.

**Comment by LekoArts** [comment]
Hey, thanks for the comment!

I fixed it with https://github.com/LekoArts/portfolio-v2/commit/59c793de9ccefef03fe0418ca8a997f616a7a7b7 - but now one really traded it with a short flash of the full list (+ light color mode when currently in dark mode). I'm fine with that for now, at least there's no error in the console anymore.
