### ISSUE TITLE
infinite redirect/refresh occuring on /garden

### ISSUE THREAD

**Issue by Rob-Rychs** [LekoArts/portfolio-v2#57]
Hi there!
I just want to let you know that in both regular and incognito mode the page at /garden url seems to be constantly refreshing making it mostly unusable.
I've actually been working on combining some elements of your portfolio-v2 into a cara landign page with an overlay menu structure when i noticed this as i wanted to inspect and see how you handled the tag sort on /garden
appreciate all the work you do on gatsby and OSS!

**Comment by LekoArts** [comment]
Thanks, must have been the upgrade to Gatsby 5 Beta. I rolled that upgrade back and it works now again.
