### ISSUE TITLE
I want to  use this template and upload it to Netlify

### ISSUE THREAD

**Issue by Husam-Almiyah** [LekoArts/portfolio-v2#68]
Hello, 

when I delpoy this to Netlify, I have to suffex the url with `www/public`

why should I use the url normally? 

Thanks @LekoArts @julienp

**Comment by LekoArts** [comment]
As per the [README](https://github.com/LekoArts/portfolio-v2/blob/main/README.md) you're not allowed to use this as your site:

> Do not do any non-commercial/commercial stuff with it, e.g. selling it or creating your own site with it. This has worked in the past and I'd like to keep the code open to everyone, but if I see ripoffs on the internet I'll make this repository private. Thanks for understanding!

Please respect that
